name: my_intermat
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - alignn=2024.5.27
  - annotated-types=0.7.0
  - ase=3.23.0
  - astunparse=1.6.3
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - babel=2.14.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blinker=1.8.2
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cmake=3.29.6
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - dgl=2.1.0
  - dm-tree=0.1.8
  - elpa=2021.11.002
  - f90wrap=0.2.15
  - fftw=3.3.10
  - filelock=3.15.4
  - flake8=7.1.0
  - flask=3.0.3
  - flatbuffers=24.3.25
  - fonttools=4.53.0
  - freetype=2.12.1
  - fsspec=2024.6.1
  - gast=0.5.5
  - gawk=5.3.0
  - gcc_impl_linux-64=11.4.0
  - gcc_linux-64=11.4.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gfortran_impl_linux-64=11.4.0
  - gfortran_linux-64=11.4.0
  - ghp-import=2.1.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-pasta=0.2.0
  - gpaw=24.6.0
  - gpaw-data=0.9.20000
  - grpcio=1.62.2
  - gsl=2.7
  - gxx_impl_linux-64=11.4.0
  - gxx_linux-64=11.4.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - importlib-resources=6.4.0
  - inflect=7.3.0
  - itsdangerous=2.2.0
  - jarvis-tools=2024.5.10
  - jinja2=3.1.4
  - joblib=1.4.2
  - keras=3.1.0
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kim-api=2.3.0
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lammps=2024.02.07
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libcblas=3.9.0
  - libcurl=8.8.0
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpnetcdf=1.12.3
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libsanitizer=11.4.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libtorch=2.3.1
  - libunistring=0.9.10
  - liburing=2.6
  - libuuid=2.38.1
  - libuv=1.48.0
  - libvdwxc=0.4.0
  - libwebp-base=1.4.0
  - libxc=6.2.2
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - make=4.3
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mergedeep=1.3.4
  - metis=5.1.1
  - mkdocs=1.6.0
